# Generated by Django 2.2.1 on 2020-12-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('idd', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.CharField(blank=True, max_length=100, null=True)),
                ('datos', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
